# 엄밀한 DPMM-MoE-SAC 설정

# 환경 설정
environment:
  name: "ant_push"
  num_envs: 1
  max_episode_steps: 1000
  cube_position: [2.0, 0.0, 0.1]
  goal_position: [3.0, 0.0, 0.1]

# DPMM 파라미터 (논문 기반)
dpmm:
  alpha: 1.0              # 집중 파라미터
  sigma_sq: 1.0           # 기본 분산
  tau_birth: 1e-4         # Birth threshold
  tau_merge: 0.5          # Merge threshold
  latent_dim: 32          # 잠재 공간 차원

# SAC 파라미터 (표준)
sac:
  gamma: 0.99             # 할인 인자
  tau: 0.005              # 소프트 업데이트 비율
  lr: 3e-4                # 학습률
  batch_size: 256         # 배치 크기
  buffer_capacity: 100000 # 리플레이 버퍼 크기
  auto_tune_alpha: true   # 자동 온도 조정
  target_entropy: null    # -action_dim으로 자동 설정

# 네트워크 구조
networks:
  fusion_hidden_dim: 256  # Fusion encoder 은닉층
  sac_hidden_dim: 256     # SAC 네트워크 은닉층
  
# 학습 설정
training:
  max_episodes: 1000
  max_steps_per_episode: 1000
  update_frequency: 10    # 전문가 업데이트 주기
  merge_frequency: 50     # 클러스터 병합 주기
  eval_frequency: 100     # 평가 주기
  save_frequency: 200     # 저장 주기

# 언어 처리
language:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  instruction_dim: 384

# 로깅 및 시각화
logging:
  log_level: "INFO"
  save_plots: true
  plot_frequency: 50
  metrics:
    - "episode_reward"
    - "cluster_count"
    - "expert_count"
    - "birth_events"
    - "merge_events"
    - "sac_losses"

# 수학적 검증
verification:
  run_tests: true
  test_frequency: 100
  tolerance: 1e-8